"""
LoRA fine-tune Llama-3.2-3B-Instruct on the Food Pharmer SFT dataset.

Prerequisites
-------------
1. Accept Meta's license at https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct
2. huggingface-cli login   (or set HF_TOKEN env var)
3. pip install trl datasets

Run
---
    python -m training.train_llama_lora
"""
import json
import os
from pathlib import Path

import torch
from torch.utils.data import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
)
from peft import LoraConfig, get_peft_model

# ── paths ─────────────────────────────────────────────────────────────────────
# HuggingFace model id — requires Meta license + `huggingface-cli login`
MODEL_NAME = "meta-llama/Llama-3.2-3B-Instruct"
SFT_PATH   = Path("training/sft_dataset.jsonl")
OUTPUT_DIR = "outputs/llama_health_lora"

# ── device ────────────────────────────────────────────────────────────────────
if torch.cuda.is_available():
    DEVICE      = "cuda"
    TORCH_DTYPE = torch.float16
elif getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
    DEVICE      = "mps"
    TORCH_DTYPE = torch.float16   # float16 halves VRAM vs float32 on MPS
else:
    DEVICE      = "cpu"
    TORCH_DTYPE = torch.float32

print(f"Training device: {DEVICE}")


# ── dataset ───────────────────────────────────────────────────────────────────
class SFTDataset(Dataset):
    """
    Reads training/sft_dataset.jsonl (generated by prepare_sft_data.py).
    Each line: {"messages": [{"role": "user", ...}, {"role": "assistant", ...}]}
    Formats using Llama 3.2 Instruct chat template.
    """

    def __init__(self, tokenizer, data_path: Path, max_length: int = 512):
        self.tokenizer  = tokenizer
        self.max_length = max_length
        self.samples: list[str] = []

        with open(data_path) as f:
            for line in f:
                item     = json.loads(line)
                messages = item["messages"]
                # Use the tokenizer's built-in chat template if available,
                # otherwise fall back to a simple <|user|> / <|assistant|> format.
                try:
                    text = tokenizer.apply_chat_template(
                        messages,
                        tokenize=False,
                        add_generation_prompt=False,
                    )
                except Exception:
                    user      = messages[0]["content"]
                    assistant = messages[1]["content"]
                    text = (
                        f"<|begin_of_text|><|start_header_id|>user"
                        f"<|end_header_id|>\n\n{user}<|eot_id|>"
                        f"<|start_header_id|>assistant<|end_header_id|>\n\n"
                        f"{assistant}<|eot_id|>"
                    )
                self.samples.append(text)

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> dict:
        enc = self.tokenizer(
            self.samples[idx],
            truncation=True,
            max_length=self.max_length,
            padding="max_length",
            return_tensors="pt",
        )
        input_ids      = enc["input_ids"].squeeze(0)
        attention_mask = enc["attention_mask"].squeeze(0)
        labels         = input_ids.clone()
        return {"input_ids": input_ids, "attention_mask": attention_mask, "labels": labels}


# ── main ──────────────────────────────────────────────────────────────────────
def main():
    if not SFT_PATH.exists():
        raise FileNotFoundError(
            f"SFT dataset not found at {SFT_PATH}. "
            "Run `python -m training.prepare_sft_data` first."
        )

    print(f"Loading tokenizer from {MODEL_NAME} ...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    print(f"Loading base model ({TORCH_DTYPE}, device={DEVICE}) ...")
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        dtype=TORCH_DTYPE,
        # device_map="auto" only works on CUDA; move manually for MPS/CPU
        device_map="auto" if DEVICE == "cuda" else None,
        low_cpu_mem_usage=True,
    )
    if DEVICE != "cuda":
        model = model.to(DEVICE)

    # LoRA adapter
    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    dataset = SFTDataset(tokenizer, SFT_PATH)
    print(f"Training samples: {len(dataset)}")

    training_args = TrainingArguments(
        output_dir=OUTPUT_DIR,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        num_train_epochs=3,
        learning_rate=2e-4,
        warmup_steps=10,
        logging_steps=10,
        save_steps=200,
        save_total_limit=2,
        bf16=DEVICE == "cuda",
        fp16=DEVICE == "mps",
        # Disable evaluation so no eval_dataset needed
        do_eval=False,
        report_to=[],
        # MPS workarounds: no pinned memory, no worker processes (avoids deadlock on macOS)
        dataloader_pin_memory=False,
        dataloader_num_workers=0,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
    )

    trainer.train()
    trainer.save_model(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    print(f"LoRA fine-tuned model saved to: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
